title: "BaldGuyHonza"
theme: minima
include: ["style.css"]
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - index.md
  - posts.md
  - about.md
  - category-philosophy.md
  - category-science.md
  - category-personal.md
