title: "BaldGuyHonza"
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - index.md
  - posts.md
  - about.md
  - category-philosophy.md
  - category-personal.md

minima:
  skin: classic
  include:
    - assets/custom-styles.css

include:
  - assets/enso-circle-final.jpg
